#ifndef    ENTER_EVENT_HXX
# define   ENTER_EVENT_HXX

# include "EnterEvent.hh"

namespace sdl {
  namespace core {
    namespace engine {

      inline
      EnterEvent::EnterEvent(const utils::Vector2f& coordinates,
                             EngineObject* receiver):
        Event(Event::Type::Enter,
              receiver,
              std::string("enter_event_") + coordinates.toString()),
        m_coordinates(coordinates)
      {}

      inline
      EnterEvent::~EnterEvent() {}

      inline
      const utils::Vector2f&
      EnterEvent::getMousePosition() const noexcept {
        return m_coordinates;
      }

      inline
      bool
      EnterEvent::equal(const Event& other) const noexcept {
        // We could set enter events to be equal only if the enter coordinates
        // are identical. Technically it is true. But for all intent and
        // purposes two enter events should be considered similar no matter the
        // associated coordinates.
        // When we will handle multiple pointing devices we might want to add
        // a check to determine whether both events have been generated by the
        // same pointing device but until then there's no need to specialize
        // further this function.
        return Event::equal(other);
      }

    }
  }
}

#endif    /* ENTER_EVENT_HXX */
